/* Called only after the existing parent passphrase gate succeeds. */
(() => {
 'use strict';
 const S=window.ELAStore,C=window.ELA_CURRICULUM,e=S.esc;
 const dims={
  'Idea development':['No developed idea yet','Idea present but thin','Clear idea with some development','Focused idea developed thoughtfully'],
  'Organization':['No discernible plan','Some order; connections need work','Logical order with beginning and ending','Purposeful order and effective connections'],
  'Supporting details / evidence':['No relevant support yet','General or weakly connected support','Specific relevant support with some explanation','Well-chosen support clearly explained'],
  'Paragraph development':['No paragraph development yet','Main idea present; elaboration limited','Focused paragraphs with detail and explanation','Unified, developed paragraphs that work together'],
  'Sentence construction':['Meaning often blocked','Meaning emerges; frequent boundary problems','Mostly clear, complete sentences','Clear, varied sentences used purposefully'],
  'Conventions':['Errors often block meaning','Frequent errors; meaning usually recoverable','Mostly controlled conventions','Consistently controlled conventions']
 };
 const assistance=['0 — Independent','1 — Minimal prompt/reminder','2 — Moderate guidance','3 — Substantial step-by-step support'];
 function options(labels,value){return '<option value="">Not recorded</option>'+labels.map((v,i)=>`<option value="${i}" ${String(value)===String(i)?'selected':''}>${e(v)}</option>`).join('');}
 function parentData(){return S.read(S.reviewKey,{reviews:{}});}
 function saveReview(id,key,value){const p=parentData();p.reviews??={};p.reviews[id]??={};p.reviews[id][key]=value;p.reviews[id].updatedAt=new Date().toISOString();S.write(S.reviewKey,p);}
 function render(){
  const host=document.getElementById('ela-parent');if(!host)return;
  const p=parentData(),works=S.evidence(),release=S.read(S.prefix+'release'),final=works['ela7-w7-3'];
  host.innerHTML=`<h2>Seven-week ELA writing bridge</h2><p>Primary target: thoughts → brainstorm → organize → outline → paragraphs → composition. Weeks 1–2 prioritize ideas, organization, and completion. Increase expectations for sentence control and conventions as writing becomes more independent. Evaluate dimensions separately; no combined mechanics-heavy grade is calculated.</p><p>Teaching emphasis: independently initiating, organizing, and producing complete compositions. Record actual assistance each time; a more independent draft can show greater progress than a heavily assisted polished piece.</p><p><a href="https://www2.cde.ca.gov/cacs/ela?c2=17%2C7%2C1%2C3" target="_blank" rel="noopener">California ELA standards</a> · This composition bridge addresses selected Grade 7 writing and language expectations; it is not a full ELA course or proof of complete standards mastery. Agreement, apostrophes, and parenthetical punctuation also revisit prerequisite conventions.</p>
  <div class="actions no-print"><button id="ela-export">Export ELA evidence and parent review</button></div>
  <h3>Independence across weeks</h3><div class="ela-table-wrap"><table class="report-table"><thead><tr><th>Week / support</th><th>Completed</th><th>Assistance observations</th></tr></thead><tbody>${C.weeks.map(w=>{const as=C.assignments.filter(a=>a.week===w.week);const counts=[0,0,0,0];let missing=0;as.filter(a=>works[a.id]?.complete).forEach(a=>{const v=p.reviews?.[a.id]?.assistance;if(v===''||v===undefined)missing++;else counts[Number(v)]++;});return `<tr><td>${w.week} · ${e(w.scaffolding)}</td><td>${as.filter(a=>works[a.id]?.complete).length}/${as.length}</td><td>${counts.map((n,i)=>`${i}: ${n}`).join(' · ')} · Unrecorded: ${missing}</td></tr>`;}).join('')}</tbody></table></div>
  <section class="panel no-print"><h3>Release the independent final prompt</h3><p>Complete Week 7 language practice first. Confirm this prompt has not been used or rehearsed with Brody. Replace it if it overlaps his earlier topics. Do not give a thesis, reasons, examples, sentence starters, or a completed outline. He may use blank planning paper or the blank on-screen spaces. Record any assistance honestly; assistance does not erase the work sample.</p>${release?`<p>Released ${e(new Date(release.releasedAt).toLocaleString())}. ${final?.stage===4?'Final task completed.':'Prompt is fixed to preserve this assessment attempt.'}</p><div class="ela-response">${e(release.prompt)}</div>`:`<label>New argument prompt<textarea id="ela-prompt" rows="4">What is one change that would make a shared space you use work better for everyone? Write an argument defending your proposed change.</textarea></label><label class="ela-check"><input id="ela-novel" type="checkbox">I confirm that this prompt is new to Brody, has not been rehearsed, and the language practice is complete.</label><button id="ela-release" class="button">Release final prompt</button>`}<p id="ela-parent-status" role="status"></p></section>
  <h3>Assignment evidence and separate review dimensions</h3><p>Quality scale: 0 = not yet demonstrated, 1 = emerging, 2 = developing, 3 = established in this sample. Leave a dimension unrecorded when evidence is insufficient or the task does not call for it. Independence uses the separate assistance scale, where 0 means independent. These observations support instructional planning.</p>
  ${C.assignments.map(a=>{const w=works[a.id],r=p.reviews?.[a.id]||{};return `<details class="panel ela-evidence" data-review="${a.id}"><summary>Week ${a.week}.${a.sequence} · ${e(a.title)} · ${w?.complete?'Complete':w?'In progress':'Not started'}</summary><p>California: ${e(a.standards.join(', '))} · ${e(a.kind)}</p><div class="ela-rubric no-print">${Object.entries(dims).map(([d,labels])=>`<label>${e(d)}<select data-review-id="${a.id}" data-dimension="${e(d)}">${options(labels.map((s,i)=>i+' — '+s),r[d])}</select></label>`).join('')}<label>Independence / assistance required<select data-review-id="${a.id}" data-dimension="assistance">${options(assistance,r.assistance)}</select></label></div><p>${Object.keys(dims).map(d=>e(d)+': '+e(r[d]??'Not recorded')).join(' · ')}<br>Independence: ${e(assistance[r.assistance]||'Not recorded')}</p>${a.independent?`<div class="ela-rubric no-print">${a.fields.map(f=>`<label>${e(f.label)} — assistance<select data-review-id="${a.id}" data-dimension="assistance-${f.id}">${options(assistance,r['assistance-'+f.id])}</select></label>`).join('')}</div><p>${a.fields.map(f=>e(f.label)+': '+e(assistance[r['assistance-'+f.id]]||'Not recorded')).join(' · ')}</p>`:''}<label class="no-print">Parent comments — assistance given, observation, next step<textarea data-review-id="${a.id}" data-dimension="comments" rows="3">${e(r.comments||'')}</textarea></label><p class="ela-response">${e(r.comments||'No parent comments recorded.')}</p>${w?a.fields.map(f=>`<h4>${e(f.label)}</h4><div class="ela-response">${e(w.fields[f.id]||'(No response)')}</div>`).join(''):'<p>No saved work yet.</p>'}${w?.snapshots.length?`<details><summary>Dated snapshots (${w.snapshots.length})</summary>${w.snapshots.map(s=>`<h4>${e(s.label)} · ${e(s.at)}</h4>${Object.entries(s.fields).map(([id,v])=>`<p><strong>${e(a.fields.find(f=>f.id===id)?.label||id)}</strong></p><div class="ela-response">${e(v)}</div>`).join('')}`).join('')}</details>`:''}<p class="ela-review-status" role="status"></p></details>`;}).join('')}`;
  host.querySelectorAll('[data-review-id]').forEach(el=>el.addEventListener(el.tagName==='TEXTAREA'?'input':'change',()=>{const status=el.closest('[data-review]').querySelector('.ela-review-status');try{saveReview(el.dataset.reviewId,el.dataset.dimension,el.value);status.textContent='Parent review saved.';}catch(error){status.textContent='NOT SAVED: '+error.message;}}));
  document.getElementById('ela-export').onclick=()=>S.download('brody-ela-evidence-and-review.json',{schemaVersion:1,student:'Brody',schoolYear:C.schoolYear,exportedAt:new Date().toISOString(),curriculum:C,elaEvidence:S.evidence(),elaParent:parentData(),elaRelease:S.read(S.prefix+'release')});
  if(document.getElementById('ela-release'))document.getElementById('ela-release').onclick=()=>{const prompt=document.getElementById('ela-prompt').value.trim(),status=document.getElementById('ela-parent-status');if(!prompt||!document.getElementById('ela-novel').checked){status.textContent='Enter the prompt and confirm that it is new and the language practice is complete.';return;}try{S.write(S.prefix+'release',{prompt,releasedAt:new Date().toISOString()});render();}catch(error){status.textContent='Prompt was NOT saved: '+error.message;}};
 }
 function backup(){return {elaEvidence:S.evidence(),elaParent:parentData(),elaRelease:S.read(S.prefix+'release')};}
 function restore(imported){
  S.merge(imported.elaEvidence);
  if(imported.elaParent){const current=parentData();current.reviews={...imported.elaParent.reviews,...current.reviews};S.write(S.reviewKey,current);}
  if(imported.elaRelease&&!S.read(S.prefix+'release'))S.write(S.prefix+'release',imported.elaRelease);
 }
 window.ELAParent={render,backup,restore};
})();
