(() => {
 'use strict';
 const S=window.HistoryStore,C=S.C,e=S.esc,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
 let active=null,saveFailed=false,externalConflict=false;
 const phases=['Massachusetts review and confirmation','California ancient-world sequencing bridge','California Grade 7 on-ramp'];
 const assistance=['Independent — no help on the demonstration','Brief reminder or prompt','Guided discussion or some modeling','Step-by-step help'];
 const timeline=()=>'<ol class="history-timeline">'+C.romanTimeline.map(x=>`<li><strong>${e(x.label)}</strong>${e(x.when)}</li>`).join('')+'</ol>';
 function fail(error){$('history-error').hidden=false;$('history-error').textContent=error.message+' Saved diagnostic and other subject records are unchanged.';}
 const sources=ids=>'<ul class="history-sources">'+ids.map(id=>{const s=C.sources.find(x=>x.id===id);return s?`<li><a href="${e(s.url)}" target="_blank" rel="noopener">${e(s.title)}</a> — ${e(s.description)}</li>`:''}).join('')+'</ul>';
 const flow=()=>'<div class="history-flow" aria-label="Lesson rhythm">'+['WATCH','DISCUSS','LOCATE','CONNECT','ANALYZE','DEMONSTRATE'].map(x=>'<span>'+x+'</span>').join('')+'</div>';
 function menu(){return '<nav class="history-sidebar" aria-label="History weeks"><a href="history-bridge.html">Course overview</a>'+C.weeks.map(w=>`<a href="history-bridge.html?week=${w.number}" ${active?.week===w.number||Number(params.get('week'))===w.number?'aria-current="page"':''}>Week ${w.number} · ${e(w.title)}<small>${e(w.phase)}</small></a>`).join('')+'</nav>';}
 function overview(){
  const weeks=params.get('week')?C.weeks.filter(w=>w.number===Number(params.get('week'))):C.weeks;
  if(!weeks.length)throw Error('This History week was not found. Return to the course overview.');
  $('history-app').innerHTML=flow()+`<div class="history-grid">${menu()}<div><section class="panel"><h2>${weeks.length===1?'Week '+weeks[0].number+' · '+e(weeks[0].title):'A coherent story, one week at a time'}</h2><p>Watch short history lessons with Dad, talk through the ideas, locate places, connect civilizations, and explain what the evidence supports. Sean chooses the videos and leads one substantial discussion each week. Take breaks and split a lesson when needed.</p><p class="history-note">Weeks 1–2 review Massachusetts Grade 6. Weeks 3–6 teach the California ancient-world sequence. Week 7 prepares you to discuss the transformation of Rome. Week 6 is new instruction.</p><div class="actions"><a href="parent.html#history-parent">Sean's lesson guides and records</a><button id="history-export-work">Export my History work</button></div></section><div class="history-week-grid">${weeks.map(w=>`<section class="panel history-week-card"><span class="badge">Week ${w.number} · ${e(w.phase)}</span><h3>${e(w.title)}</h3><p>${e(w.purpose)}</p><p><strong>Dad's big question:</strong> ${e(w.bigQuestion)}</p><ol>${w.sessions.map(s=>{const v=S.work(s.id);return `<li><a href="history-bridge.html?id=${s.id}">${e(s.title)}</a><p class="history-note">About ${s.minutes} minutes · ${v.complete?'Demonstration saved':v.updatedAt?'Work in progress':'Not started'}</p></li>`;}).join('')}</ol><details><summary>Week ${w.number} demonstration</summary><p>${e(w.weeklyDemonstration.task)}</p><ul>${w.weeklyDemonstration.criteria.map(c=>'<li>'+e(c)+'</li>').join('')}</ul></details></section>`).join('')}</div>${weeks.some(w=>w.number>=6)?`<section class="panel"><h2>The Roman story</h2>${timeline()}<p class="history-note">These stages overlap in places. 476 CE is a conventional marker for the end of western imperial rule, not the disappearance of Roman people, institutions, or the eastern empire.</p></section>`:''}<section class="panel"><h3>Use evidence, not trivia</h3><p>Geography → settlement → civilization → government, culture and economy → contact → change → cause and effect → historical evidence.</p><p>For a short explanation, use <strong>question → claim → evidence → explanation</strong>. A labeled map, a spoken explanation recorded by Sean, a timeline, or a few careful sentences can each show learning.</p></section></div></div>`;
  $('history-export-work').onclick=exportWork;
 }
 function field(id,label,value,rows=4){return `<label>${e(label)}<textarea data-history-field="${id}" rows="${rows}">${e(value||'')}</textarea></label><div class="history-print-only history-response">${e(value||'No response recorded.')}</div>`;}
 function select(id,label,values,value){return `<label>${e(label)}<select data-history-field="${id}"><option value="">Choose / record honestly</option>${values.map(x=>`<option ${value===x?'selected':''}>${e(x)}</option>`).join('')}</select></label><p class="history-print-only">${e(label)}: ${e(value||'Not recorded')}</p>`;}
 function lesson(){
  active=S.lessons().find(x=>x.id===params.get('id'));if(!active)throw Error('This History lesson was not found.');
  const w=C.weeks.find(w=>w.number===active.week),s=active,v=S.work(s.id),f=v.fields,all=S.lessons(),index=all.findIndex(x=>x.id===s.id);
  document.title=s.title+' · History with Dad';
  $('history-app').innerHTML=flow()+`<div class="history-grid">${menu()}<div><section class="panel"><span class="badge">Week ${w.number} · ${e(w.phase)}</span><h2>${e(s.title)}</h2><p class="history-note">About ${s.minutes} minutes · ${e(s.mode.replaceAll('-',' '))} · Brody and Sean</p><ul>${s.objectives.map(o=>'<li>'+e(o)+'</li>').join('')}</ul><details><summary>Standards addressed in this week's work</summary><ul>${w.standards.map(x=>'<li><strong>'+e(x.code)+'</strong> · '+e(x.label)+'</li>').join('')}</ul><p class="history-note">Selected expectations are addressed; one lesson is not proof of full standards mastery.</p></details></section>
  <section class="panel"><div class="history-video"><p class="eyebrow">Watch · Video lesson slot</p><h3>${e(s.video.topic)}</h3><p>Watch today's history lesson with Dad. Sean may choose an age-appropriate animated lesson or teach the ideas directly.</p><p>Suggested YouTube search:</p><p class="history-search">${e(s.video.search)}</p><p>Desired length: ${e(s.video.length)}</p><strong>Listen for</strong><ul>${s.video.listenFor.map(x=>'<li>'+e(x)+'</li>').join('')}</ul></div>${field('video','Video title / creator or link actually used (or “Sean taught this directly”)',f.video,2)}${field('watchNotes','An idea or question to discuss with Dad',f.watchNotes,2)}<details class="history-reading"><summary>Read or discuss the lesson story with Sean</summary>${s.learn.map(p=>'<p>'+e(p)+'</p>').join('')}</details>
  ${s.activities.map(a=>`<section class="history-activity"><p class="eyebrow">${e(a.stage)}</p><h3>${e(a.title)}</h3><p class="history-response">${e(a.instructions)}</p>${field(a.stage.toLowerCase(),'Your '+a.stage.toLowerCase()+' notes / map labels / timeline / explanation',f[a.stage.toLowerCase()],3)}</section>`).join('')}</section>
  <section class="panel"><p class="eyebrow">Demonstrate · ${e(s.evidence.kind)}</p><h2>Show what you can explain</h2><p>${e(s.evidence.prompt)}</p><ul>${s.evidence.criteria.map(x=>'<li>'+e(x)+'</li>').join('')}</ul><p class="history-note">Try this part yourself first. If you use help, record it. For a map or diagram made on paper, describe the work and optionally link a private work sample. For oral work, record your explanation or ask Sean to note what you said.</p>${field('demonstrate','Your demonstration — claim, evidence, and explanation, or an account of your oral / map work',f.demonstrate,7)}<label>Optional work-sample link<input data-history-field="artifact" type="url" placeholder="https://…" value="${e(f.artifact||'')}"></label><div class="history-form-grid">${select('responseMode','Demonstration format',['Short written explanation','Oral explanation to Sean','Map / diagram / comparison','Timeline / event sequence','Mixed work sample'],f.responseMode)}${select('assistance','Help used on this demonstration',assistance,f.assistance)}</div><p id="history-save-status" class="history-status" role="status">${v.updatedAt?'Work saved locally. '+(v.complete?'A demonstration checkpoint is on record.':''):'Your work saves in this browser as you type.'}</p><div class="actions history-no-print"><button id="history-save-checkpoint">Save demonstration checkpoint</button><button id="history-export-work">Export my History work</button><button id="history-print">Print this lesson and work</button></div><p class="history-note">A saved checkpoint marks the assignment complete. Sean records what the evidence demonstrates in the parent area. You may revise your draft; earlier checkpoints remain on record.</p><details><summary>Dated checkpoints (${v.snapshots.length})</summary>${v.snapshots.map(x=>`<article class="history-checkpoint"><h3>${e(new Date(x.at).toLocaleString())}</h3><p>${e(x.fields.responseMode)} · ${e(x.fields.assistance)}</p><div class="history-response">${e(x.fields.demonstrate)}</div>${x.fields.artifact?'<p>Work sample: '+e(x.fields.artifact)+'</p>':''}</article>`).join('')||'<p>No demonstration checkpoint saved yet.</p>'}</details></section>
  <section class="panel"><details><summary>Historical sources and further viewing</summary>${sources(s.sources)}<p class="history-note">Ancient objects and texts are evidence. The lesson descriptions are modern summaries unless a quotation is explicitly identified. Use the linked records to check context and limits.</p></details></section><nav class="actions history-no-print" aria-label="Lesson order">${index>0?`<a href="history-bridge.html?id=${all[index-1].id}">← Previous lesson</a>`:''}<a href="history-bridge.html?week=${w.number}">Week ${w.number} overview</a>${index<all.length-1?`<a href="history-bridge.html?id=${all[index+1].id}">Next lesson →</a>`:'<a href="parent.html#history-parent">Review the bridge with Sean</a>'}</nav></div></div>`;
  document.querySelectorAll('[data-history-field]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{try{if(externalConflict)throw Error('Another tab changed this lesson. Export this draft and reload before saving.');S.save(s.id,v=>{v.fields[el.dataset.historyField]=el.value;});saveFailed=false;$('history-save-status').textContent='Saved in this browser.';$('history-error').hidden=true;}catch(error){saveFailed=true;fail(error);$('history-save-status').textContent='Not saved. Export your work before leaving this page.';}}));
  $('history-save-checkpoint').onclick=()=>{try{const fields=currentFields();if(!fields.demonstrate.trim()||!fields.responseMode||!fields.assistance)throw Error('Add your demonstration and record its format and the help used.');if(fields.artifact&&!/^https?:\/\//i.test(fields.artifact))throw Error('Use an http or https work-sample link, or leave it blank.');S.save(s.id,v=>{v.fields=fields;v.snapshots.push({id:crypto.randomUUID(),at:new Date().toISOString(),fields:structuredClone(fields)});v.complete=true;});S.syncPortal();saveFailed=false;lesson();$('history-save-status').textContent='Demonstration checkpoint saved. Sean can now review the evidence.';}catch(error){fail(error);}};
  $('history-export-work').onclick=exportWork;$('history-print').onclick=()=>window.print();
 }
 function currentFields(){return Object.fromEntries([...document.querySelectorAll('[data-history-field]')].map(el=>[el.dataset.historyField,el.value]));}
 function exportWork(){try{const b=S.backup();if(active){b.lessonRecords[active.id]??=S.work(active.id);b.lessonRecords[active.id].fields=currentFields();}S.download('brody-history-work.json',{kind:'history-bridge',schemaVersion:1,student:'Brody',exportedAt:new Date().toISOString(),historyBridge:b,includesUnsavedDraft:saveFailed});}catch(error){fail(error);}}
 window.addEventListener('beforeprint',()=>{document.querySelectorAll('#history-app details').forEach(d=>d.open=true);document.querySelectorAll('[data-history-field]').forEach(el=>{const printed=el.parentElement.nextElementSibling;if(printed?.classList.contains('history-print-only'))printed.textContent=el.value||'Not recorded';});});
 window.addEventListener('storage',event=>{if(active&&event.key===S.prefix+active.id){externalConflict=true;saveFailed=true;$('history-save-checkpoint').disabled=true;$('history-error').hidden=false;$('history-error').textContent='This lesson changed in another tab. Export your current draft before reloading to see the latest saved work.';}});
 try{params.has('id')?lesson():overview();}catch(error){$('history-app').innerHTML='<p><a href="history-bridge.html">Return to the History overview</a> · <a href="index.html#history">Home School</a></p>';fail(error);}
})();
