const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const {chromium}=require('playwright');
const source=path.resolve(__dirname,'..')+path.sep,base=process.env.HISTORY_QA_URL||'http://127.0.0.1:8765/Brodys-Homeschool/',out=process.env.HISTORY_QA_OUT||__dirname,results=[],pass=x=>{results.push(x);console.log('PASS '+x)};
const map=new Map(),ctx={window:{},localStorage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},structuredClone,Date,console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(source+'history-course.js','utf8'),ctx);vm.runInContext(fs.readFileSync(source+'history-store.js','utf8'),ctx);const S=ctx.window.HistoryStore,id='hb-w1-s1';
const valid={schemaVersion:1,fields:{demonstrate:'Current'},snapshots:[{id:'newer',at:'2026-09-03T12:00:00Z',fields:{demonstrate:'Newer work'}}],complete:true,updatedAt:'2026-09-03T12:00:00Z'};
S.write(S.prefix+id,valid);const bad=structuredClone(valid);bad.updatedAt=null;const before=JSON.stringify([...map]);assert.throws(()=>S.restore({schemaVersion:1,courseVersion:'2026.1',lessonRecords:{[id]:bad}}));assert.equal(JSON.stringify([...map]),before);
pass('Malformed completed records are rejected before storage mutation');
S.write(S.parentKey,{schemaVersion:1,lessons:{[id]:{status:'Practiced',observations:[{id:'local',at:'2026-09-03T12:00:00Z',taught:'Local observation'}]}},weeks:{},summary:{}});
const incoming=structuredClone(valid);incoming.snapshots=[{id:'older',at:'2026-09-01T12:00:00Z',fields:{demonstrate:'Older work'}}];incoming.fields.demonstrate='Incoming';
S.restore({schemaVersion:1,courseVersion:'2026.1',lessonRecords:{[id]:incoming},parentReview:{schemaVersion:1,lessons:{[id]:{status:'Introduced',observations:[{id:'earlier',at:'2026-09-01T12:00:00Z',taught:'Earlier observation'}]}},weeks:{},summary:{}}});assert.equal(S.work(id).snapshots.at(-1).id,'newer');assert.equal(S.work(id).fields.demonstrate,'Current');assert.equal(S.parent().lessons[id].status,'Practiced');assert.equal(S.parent().lessons[id].observations.length,2);
pass('Restore orders checkpoints by date and merges teaching observations without replacing current findings');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{
 const context=await browser.newContext(),page=await context.newPage();page.on('dialog',d=>d.accept().catch(()=>{}));await page.goto(base+'parent.html');await page.locator('#parent-pass').fill('SyntheticDraft123');await page.locator('#confirm-pass').fill('SyntheticDraft123');await page.locator('#unlock button').click();await page.waitForSelector('[data-history-week="1"]');await page.locator('[data-history-week="1"] > summary').click();
 for(const lesson of ['hb-w1-s1','hb-w1-s2']){const f=page.locator('[data-history-review="'+lesson+'"]');await f.locator('..').locator('summary').first().click();await f.locator('[name="taught"]').fill('Saved draft '+lesson);}
 await page.locator('[data-history-review="hb-w1-s1"] button[type="submit"]').click();await page.locator('#refresh-parent').click();await page.waitForSelector('[data-history-week="1"]');await page.locator('[data-history-week="1"] > summary').click();const f=page.locator('[data-history-review="hb-w1-s2"]');await f.locator('..').locator('summary').first().click();assert.equal(await f.locator('[name="taught"]').inputValue(),'Saved draft hb-w1-s2');assert.equal(await page.evaluate(()=>HistoryStore.parent().lessons['hb-w1-s2']),undefined);assert.equal(await page.evaluate(()=>HistoryParent.summary().pendingTeachingDrafts),1);
 pass('Editing two parent forms, saving one, and refreshing preserves the other draft without treating it as taught');
 const csvReady=page.waitForEvent('download');await page.locator('#history-export-csv').click();const csv=fs.readFileSync(await(await csvReady).path(),'utf8');assert(csv.includes('Saved draft hb-w1-s1'));assert(!csv.includes('Saved draft hb-w1-s2'));assert(csv.includes('recordedInstructionType'));
 await page.locator('[data-history-summary="section10"]').fill('Fresh handoff note saved immediately before printing.');await page.evaluate(()=>window.print=()=>{});await page.locator('#history-print-summary').click();assert((await page.locator('#history-summary').innerText()).includes('Fresh handoff note saved immediately before printing.'));assert(!(await page.locator('#history-summary').innerText()).includes('Saved draft hb-w1-s2'));await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));await page.locator('[data-history-summary="section10"]').fill('Summary still saves after print.');assert.equal(await page.evaluate(()=>HistoryStore.parent().summary.section10),'Summary still saves after print.');
 pass('Teaching CSV excludes drafts; print refreshes saved summary notes and keeps note editing functional');

 await page.goto(base+'history-bridge.html?id=hb-w1-s1');await page.locator('[data-history-field="demonstrate"]').fill('First tab draft');const other=await context.newPage();await other.goto(base+'history-bridge.html?id=hb-w1-s1');await other.locator('[data-history-field="demonstrate"]').fill('Second tab latest');await page.waitForFunction(()=>document.getElementById('history-save-checkpoint').disabled);await page.locator('[data-history-field="demonstrate"]').fill('Stale first tab edit');assert.equal(await page.evaluate(()=>HistoryStore.work('hb-w1-s1').fields.demonstrate),'Second tab latest');
 pass('A stale tab cannot overwrite newer History work');
 await context.close();fs.writeFileSync(path.join(out,'history-edge-qa-results.json'),JSON.stringify({passed:true,groups:results,date:new Date().toISOString(),syntheticOnly:true},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
